### ISSUE TITLE
Problem with version 28

### ISSUE THREAD

**Issue by stefaanbolle** [fdebrus/Nikobus-HA#20]
When upgrading to version 28 I cannot switch switches anymore. Error "kan service... Niet aanroepen". Rolling back to version 22 makes it working again.

**Comment by fdebrus** [comment]
Thanks for reporting the issue, as time allow, could you submit a debug log ? 

Have you updated your module_config.json file according the readme for the .28 release ? 

Your channels for all modules need to be updated to 

{"description": "S1 Output 1", **"led_on":"259B02", "led_off":"659B02"**} for entries with feedback led
{"description": "S1 Output 2", **"led_on":"", "led_off":""**}, for entries without feedback led

same for shuters, etc... 

 {"description": "R1 output_1", "operation_time": "40", "led_on":"", "led_off":""}

**Comment by stefaanbolle** [comment]
Yep, that did the trick! Did not read through the needed confg changes. Thanks!

**Comment by stefaanbolle** [comment]
I had to modify the config files. RTFM
