### ISSUE TITLE
Long Press doesn't work anymore

### ISSUE THREAD

**Issue by Timo-Me** [fdebrus/Nikobus-HA#24]
HI,

The nikobus_button_pressed_3 doesn't work anymore with the latest release.
I can't go back to an earlier release in HA as this doesn't work work a lower version of the core.
Can you check?

Thanks

**Comment by fdebrus** [comment]
Not sure I get you, does it stop working with the latest release of Nikobus-HA or HomeAssistant core ? the problem surfaced as you upgraded Nikobus-HA to the latest or HomeAssistant core or supervisor upgrade ?

**Comment by Timo-Me** [comment]
HI,

This is the version i have:
Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

HACS Nikobus : 2024.11.11

Since the latest update to Nikobus 2024.11.11 yesterday none of the long press action I programmed don't work anymore.

Example YAML:

alias: Alles Uit
description: ""
triggers:
  - event_type: nikobus_button_pressed_3
    event_data:
      address: XXXXXX
    trigger: event
conditions: []
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.s3_out_10
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.s3_out_12
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.s2_out_11
mode: single


None of the long press events is in the logbook anymore and the above automation is not triggered as well.
I hope this helps to clarify.

Thanks

**Comment by fdebrus** [comment]
yeap, thank you, looking at

**Comment by fdebrus** [comment]
I solved my problem and I can reproduce yours. Working on

**Comment by fdebrus** [comment]
New release, have a try and let me know

**Comment by Timo-Me** [comment]
Hi,
It works again. This long press button is resolved. I've been testing intensively and I found another issue where the longspress is sometimes not seen. I'll post it once I can reproduce consistently. 
Thanks for this bugfix.

**Comment by fdebrus** [comment]
You can have situation where multiple nikobus button are pressed at almost the same time. The wife factor… 

Nikobus itself will fail to process the command and so the integration will not catch something not existing. 

Look if you case is not related to this, failed Nikobus commands due to concurrency. 

We are 4 at home and this happen from time to time. Just press again

**Comment by fdebrus** [comment]
Not feedback on the issue, consider resolved. open new issue as need be
