### ISSUE TITLE
Incomplete Nikobus object instance reference in nkbactuator.py leading to tracebacks during new button discovery

### ISSUE THREAD

**Issue by bk31415** [fdebrus/Nikobus-HA#25]
Using Nikobus-HA 2024.11.19 with Home Assistant 2024.11.03 (Raspberry Pi 3 with HaOS):

In nkbactuator.py, had to modify 

175:            await self._hass.data[DOMAIN]._nikobus_config.write_json_data(

as the path to access Nikobus object from hass was incompletely specified. 

Turning that line into: 

175:            await self._hass.data[DOMAIN]["nikobus_instance"]._nikobus_config.write_json_data(

addressed the issue for me.

**Comment by fdebrus** [comment]
Very good catch, thank you ! The fix will be part of the next release.

**Comment by fdebrus** [comment]
The latest code is on the github repo, stil need to iron out the cover logic which is failing...

**Comment by fdebrus** [comment]
Fixed as proposed in release 2024.11.25
