### ISSUE TITLE
Unexpected error in event listener: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

### ISSUE THREAD

**Issue by arnaud-cortisse** [fdebrus/Nikobus-HA#27]
Hello! 

Thanks for the great work! 

Here is an issue I just encountered (2024.11.19): 
``` 
This error originated from a custom integration.

Logger: custom_components.nikobus.nkblistener
Source: custom_components/nikobus/nkblistener.py:77
integration: Nikobus (documentation, issues)
First occurred: 12:03:14 PM (1 occurrences)
Last logged: 12:03:14 PM

Unexpected error in event listener: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
Traceback (most recent call last):
  File "/config/custom_components/nikobus/nkblistener.py", line 77, in listen_for_events
    message = data.decode("utf-8").strip()
              ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
```

Now it seems like when I press physical nikobus_button, the integration don't catch them anymore.

**Comment by arnaud-cortisse** [comment]
And of course restarting home assistant made the physical nikobus_button work again :)

**Comment by fdebrus** [comment]
The error indicates that the data received by your listen_for_events function contains bytes that are not valid UTF-8 encoded characters. The byte **0x92** specifically is commonly part of Windows-1252 (a common encoding for Western languages) but is not valid in UTF-8.

I will check for the same and revert.

For my knowledge, you install the integration, reboot or restart HA ? then you have to reboot or restart again to make it work ?

**Comment by fdebrus** [comment]
Next release will use Windows-1252 vs UTF-8
I've also added "Raw data" in the debuglog which will show you want raw data you get like 0x92

Will release before and of week as time allows

2024-11-27 14:30:30.416 DEBUG (MainThread) [custom_components.nikobus.nkblistener] **Raw data received:** b'$10126C0E4E16A4\r'
2024-11-27 14:30:30.416 DEBUG (MainThread) [custom_components.nikobus.nkblistener] Received message: $10126C0E4E16A4

**Comment by arnaud-cortisse** [comment]
Hey FYI, happened to me again today :)

So, the integration has been installed for a while. It runs and then at some point I get this error message in the log. After I have had this message, the physical button don't trigger my automations anymore. 

To fix it, I need to restart home assistant, no reboot needed (restarting the integration only might cut it, haven't tried).

**Comment by fdebrus** [comment]
is it again 0x92 in the log ?

**Comment by fdebrus** [comment]
Try to use Windows-1252 vs UTF-8

**Comment by fdebrus** [comment]
Beta code is available: https://github.com/fdebrus/Nikobus-HA/tree/V2/custom_components/nikobus

**Comment by fdebrus** [comment]
No further feedback, considering issue as resolved by moving to Windows-1252

**Comment by arnaud-cortisse** [comment]
Forgot to keep you posted: I changed to source code to what you suggested and it never has crashed since
