### ISSUE TITLE
Reaction Speed Slow

### ISSUE THREAD

**Issue by Timo-Me** [fdebrus/Nikobus-HA#28]
Hi, Great improvement in stability. No more retries after a good day of testing and no errors in logs so far.
The reaction speed to change a status on the NIKOBUS Switch module is almost 3 to 5 seconds, before it was instant.
Is it possible to improve the reaction speed? Thanks

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

To improve the reaction speed of NIKOBUS Switch modules, we'll modify the NikobusSwitchEntity class to update the state more quickly and reduce delays. We'll implement an optimistic update approach and adjust the _handle_coordinator_update method.

You can review changes in this commit: https://github.com/mnmnk43434/fdebrus-Nikobus-HA-28/commit/60742f8916ecf1d3812f0dca42642a169370cc8e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by fdebrus** [comment]
@mnmnk43434 thank you for the provided code ! Will look at to integrate some logic / optimization in the current optimistic updates from release 0.2.x

**Comment by fdebrus** [comment]
I've also moved away from completion_handler (except for cover). Error handling and raising provide a faster feedback on command result that I've tested so far.

**Comment by fdebrus** [comment]
We can't get the latest status from the bus without a huge timing impact. We will continue to rely on status in memory
